### ISSUE TITLE
paper-tab should automatically upper-case text

### ISSUE THREAD

**Issue by osechet** [PolymerElements/paper-tabs#115]
As the material design's specs mentions it, the tabs text should be all caps. I think the `paper-tab` should automatically upper-case its text, probably by using using `text-transform: uppercase;`.

**Comment by bicknellr** [comment]
This is a totally valid issue but we're going to hold off on this change while we put some more thought into the scope of `paper-styles/typography.html` and how it plays with `paper-tab` and other elements.

I'm guessing you've already found this but, in the meantime, you can add this behavior with the `--paper-tab-content` mixin:
```css
paper-tab {
  --paper-tab-content: {
    text-transform: uppercase;
  };
}
```
