### ISSUE TITLE
Feature request: Control opacity on elements not selected 

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-tabs#67]
This is a request to remove or have some kind of control over(when not used in a custom element):

```css
    :host(:not(.iron-selected)) > .tab-content {
      opacity: 0.8;
    }
```
